In [1]:
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 23 17:31:11 2021
@author: Teo Bee Guan
"""

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [7]:
tickers = ["AAPL", "ABMD", "ACN", "ADBE", "AEE", "AMZN", "CPB", "CVX",
           "DLR", "DLTR", "DPZ", "EA", "EBAY", "FB", "FDX", "FOX", "GE","GOOGL",  
           "HPE", "HD", "HON", "IEX", "INTC", "JNJ", "JPM", "KMB", "LRCX", 
           "MAR", "MA", "MSFT", "MSI",  "NFLX", "NKE", "NLSN", "ORCL", "PYPL", 
           "PFE",  "QCOM", "REG", "SBUX", "TSLA", "TWTR", "UAL", "VZ",  "WFC", 
           "WDC", "XEL", "YUM", "ZION"]

stock_data = yf.download(tickers, start='2019-04-01', end='2022-07-24', interval='1mo')
# stock_data = stock_data.dropna() 

stock_data

[*********************100%***********************]  49 of 49 completed

             Adj Close                                                 \
                  AAPL        ABMD         ACN        ADBE        AEE
Date
2019-04-01   48.776451  277.410004  173.785492  289.250000  66.897339
2019-04-04         NaN         NaN         NaN         NaN        NaN
2019-04-08         NaN         NaN         NaN         NaN        NaN
2019-04-09         NaN         NaN         NaN         NaN        NaN
2019-04-10         NaN         NaN         NaN         NaN        NaN
...                ...         ...         ...         ...        ...
2022-07-11         NaN         NaN         NaN         NaN        NaN
2022-07-13         NaN         NaN         NaN         NaN        NaN
2022-07-14         NaN         NaN         NaN         NaN        NaN
2022-07-18         NaN         NaN         NaN         NaN        NaN
2022-07-22  154.089996  281.700012  288.010010  401.899994  87.430000

                                                                       ...  \
                  AMZN        CPB         CVX         DLR        DLTR  ...
Date                                                                   ...
2019-04-01   96.325996  34.646183  102.855934  105.638344  111.279999  ...
2019-04-04         NaN        NaN         NaN         NaN         NaN  ...
2019-04-08         NaN        NaN         NaN         NaN         NaN  ...
2019-04-09         NaN        NaN         NaN         NaN         NaN  ...
2019-04-10         NaN        NaN         NaN         NaN         NaN  ...
...                ...        ...         ...         ...         ...  ...
2022-07-11         NaN        NaN         NaN         NaN         NaN  ...
2022-07-13         NaN        NaN         NaN         NaN         NaN  ...
2022-07-14         NaN        NaN         NaN         NaN         NaN  ...
2022-07-18         NaN        NaN         NaN         NaN         NaN  ...
2022-07-22  122.419998  47.849998  144.190002  127.419998  172.009995  ...

                 Volume                                                      \
                   SBUX          TSLA         TWTR         UAL           VZ
Date
2019-04-01  146496900.0  1.153736e+09  402845900.0  61650400.0  272992300.0
2019-04-04          NaN           NaN          NaN         NaN          NaN
2019-04-08          NaN           NaN          NaN         NaN          NaN
2019-04-09          NaN           NaN          NaN         NaN          NaN
2019-04-10          NaN           NaN          NaN         NaN          NaN
...                 ...           ...          ...         ...          ...
2022-07-11          NaN           NaN          NaN         NaN          NaN
2022-07-13          NaN           NaN          NaN         NaN          NaN
2022-07-14          NaN           NaN          NaN         NaN          NaN
2022-07-18          NaN           NaN          NaN         NaN          NaN
2022-07-22    6283617.0  3.429246e+07   24868508.0  14579734.0   58265024.0


                    WDC          WFC         XEL         YUM        ZION
Date
2019-04-01  130994700.0  556953700.0  60972100.0  25532900.0  42017200.0
2019-04-04          NaN          NaN         NaN         NaN         NaN
2019-04-08          NaN          NaN         NaN         NaN         NaN
2019-04-09          NaN          NaN         NaN         NaN         NaN
2019-04-10          NaN          NaN         NaN         NaN         NaN
...                 ...          ...         ...         ...         ...
2022-07-11          NaN          NaN         NaN         NaN         NaN
2022-07-13          NaN          NaN         NaN         NaN         NaN
2022-07-14          NaN          NaN         NaN         NaN         NaN
2022-07-18          NaN          NaN         NaN         NaN         NaN
2022-07-22    4148988.0   15652979.0   2136234.0   1272758.0   1661616.0

[341 rows x 294 columns]

In [6]:
sp500 = yf.download("^GSPC", start='2019-04-01', end='2021-07-24', interval='1mo')
sp500

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-04-01,2848.629883,2949.520020,2848.629883,2945.830078,2945.830078,69604840000
2019-05-01,2952.330078,2954.129883,2750.520020,2752.060059,2752.060059,76860120000
2019-06-01,2751.530029,2964.149902,2728.810059,2941.760010,2941.760010,70904280000
2019-07-01,2971.409912,3027.979980,2952.219971,2980.379883,2980.379883,70349470000
2019-08-01,2980.320068,3013.590088,2822.120117,2926.459961,2926.459961,79599440000
2019-09-01,2909.010010,3021.989990,2891.850098,2976.739990,2976.739990,73992330000
2019-10-01,2983.689941,3050.100098,2855.939941,3037.560059,3037.560059,77564550000
2019-11-01,3050.719971,3154.260010,3050.719971,3140.979980,3140.979980,72179920000
2019-12-01,3143.850098,3247.929932,3070.330078,3230.780029,3230.780029,72054000000
2020-01-01,3244.669922,3337.770020,3214.639893,3225.520020,3225.520020,77104420000
2020-02-01,3235.659912,3393.520020,2855.840088,2954.219971,2954.219971,84292270000
2020-03-01,2974.280029,3136.719971,2191.860107,2584.590088,2584.590088,161801100000
2020-04-01,2498.080078,2954.860107,2447.489990,2912.429932,2912.429932,123163450000
2020-05-01,2869.090088,3068.669922,2766.639893,3044.310059,3044.310059,106799100000
2020-06-01,3038.780029,3233.129883,2965.659912,3100.290039,3100.290039,131044000000
2020-07-01,3105.919922,3279.989990,3101.169922,3271.120117,3271.120117,97197020000
2020-08-01,3288.260010,3514.770020,3284.530029,3500.310059,3500.310059,84402300000
2020-09-01,3507.439941,3588.110107,3209.449951,3363.000000,3363.000000,92084120000
2020-10-01,3385.870117,3549.850098,3233.939941,3269.959961,3269.959961,89737600000
2020-11-01,3296.199951,3645.989990,3279.739990,3621.629883,3621.629883,100977880000
2020-12-01,3645.870117,3760.199951,3633.399902,3756.070068,3756.070068,96056410000
2021-01-01,3764.610107,3870.899902,3662.709961,3714.239990,3714.239990,105548790000
2021-02-01,3731.169922,3950.429932,3725.620117,3811.149902,3811.149902,98596960000
2021-03-01,3842.510010,3994.409912,3723.340088,3972.889893,3972.889893,120863560000
2021-04-01,3992.780029,4218.779785,3992.780029,4181.169922,4181.169922,82869290000
2021-05-01,4191.979980,4238.040039,4056.879883,4204.109863,4204.109863,75155370000
2021-06-01,4216.520020,4302.430176,4164.399902,4297.500000,4297.500000,85705180000
2021-07-01,4300.729980,4429.970215,4233.129883,4395.259766,4395.259766,66496430000

In [ ]:


    



stock_returns = pd.DataFrame()

for ticker in tickers:
    stock_returns[ticker] = stock_data['Adj Close'][ticker].pct_change()

stock_returns = stock_returns.dropna()

sp500["monthly_returns"] = sp500["Adj Close"].pct_change().fillna(0)

def portfolio(data, numStocks, numRev):
    df = data.copy()
    selected_stocks = []
    avg_monthly_ret = [0]
    for i in range(len(df)):
        if len(selected_stocks ) > 0:
            avg_monthly_ret.append(df[selected_stocks].iloc[i,:].mean())
            bad_stocks = df[selected_stocks].iloc[i,:].sort_values(ascending=True)[:numRev].index.values.tolist()
            selected_stocks  = [t for t in selected_stocks if t not in bad_stocks]
        fill = numStocks - len(selected_stocks)
        new_picks = df.iloc[i,:].sort_values(ascending=False)[:fill].index.values.tolist()
        selected_stocks  = selected_stocks  + new_picks
        print(selected_stocks)
    returns_df = pd.DataFrame(np.array(avg_monthly_ret),columns=["monthly_returns"])
    return returns_df 


def CAGR(data):
    df = data.copy()
    df['cumulative_returns'] = (1 + df['monthly_returns']).cumprod()
    trading_months = 12
    n = len(df)/ trading_months
    cagr = (df['cumulative_returns'][len(df)-1])**(1/n) - 1
    return cagr

def volatility(data):
    df = data.copy()
    trading_months = 12
    vol = df['monthly_returns'].std() * np.sqrt(trading_months)
    return vol

def sharpe_ratio(data, rf):
    df = data.copy()
    sharpe = (CAGR(df) - rf)/ volatility(df)
    return sharpe 

def maximum_drawdown(data):
    df = data.copy()
    df['cumulative_returns'] =  (1 + df['monthly_returns']).cumprod()
    df['cumulative_max'] = df['cumulative_returns'].cummax()
    df['drawdown'] = df['cumulative_max'] - df['cumulative_returns']
    df['drawdown_pct'] = df['drawdown'] / df['cumulative_max']
    max_dd = df['drawdown_pct'].max()
    return max_dd
    

rebalanced_portfolio = portfolio(stock_returns, 5, 2)
print("Rebalanced Portfolio Performance")
print("CAGR: " + str(CAGR(rebalanced_portfolio)))
print("Sharpe Ratio: " + str(sharpe_ratio(rebalanced_portfolio, 0.03)))
print("Maximum Drawdown: " + str(maximum_drawdown(rebalanced_portfolio) ))

print("\n")

print("S&P500 Index Performance")
print("CAGR: " + str(CAGR(sp500)))
print("Sharpe Ratio: " + str(sharpe_ratio(sp500, 0.03)))
print("Maximum Drawdown: " + str(maximum_drawdown(sp500) ))

fig, ax = plt.subplots()
plt.plot((1+portfolio(stock_returns, 5, 2)).cumprod())
plt.plot((1+sp500["monthly_returns"].reset_index(drop=True)).cumprod())
plt.title("S&P500 Index Return vs Rebalancing Strategy Return")
plt.ylabel("cumulative return")
plt.xlabel("months")
ax.legend(["Strategy Return","Index Return"])